[package]
name = "protobuf_build"
version = "0.1.2"
authors = ["Paul Lietar <paul@lietar.net>"]
build = "build.rs"

[dependencies]
protobuf = "1.2"
libc = "0.2"

[build-dependencies]
gcc = "0.3"
pkg-config = "0.3"
